### ISSUE TITLE
No README.md

### ISSUE THREAD

**Issue by lisannevvliet** [lisannevvliet/ethical-food-checker-pwa#19]
- [x] An explanation of client- server rendering.
- [x] An activity diagram including the Service Worker.
- [x] A list of enhancements to optimize the critical render path implemented your app.

**Comment by jornveltrop** [comment]
Er mag nog meer bij dan de punten die je tot nu toe hebt genoteerd: 

- [ ] Maak een goede omschrijving van je product
- [ ] Maak een live demo link aan (Heroku misschien?)
- [ ] Maak een sectie aan over concept, install notes, data life cycle, external API en real-time events

**Comment by jornveltrop** [comment]
Maak ook een visuele lijst van alle features die je app heeft (Search, pagination, etc.) Hier mag je een beetje flexen.

Zet hierbij welke data wordt opgehaald, opgeslagen of wordt verwerkt.

**Comment by lisannevvliet** [comment]
[Check nog even of jij gebruik maakt van real-time events. Beschrijf deze indien nodig. Zo weet de lezer hoe de communicatie tussen verschillende onderdelen van je app werkt.](https://github.com/lisannevvliet/ethical-food-checker-pwa/issues/25)

**Comment by lisannevvliet** [comment]
Real-time events hoeft niet volgens Declan en Farrahton.
