### ISSUE TITLE
Real-time events

### ISSUE THREAD

**Issue by jornveltrop** [lisannevvliet/ethical-food-checker-pwa#25]
Check nog even of jij gebruik maakt van real-time events. Beschrijf deze indien nodig. Zo weet de lezer hoe de communicatie tussen verschillende onderdelen van je app werkt.

**Comment by lisannevvliet** [comment]
Duplicate issue, merged into [Documentation in README.md](https://github.com/lisannevvliet/ethical-food-checker-pwa/issues/19)
