### ISSUE TITLE
Comments in service-worker

### ISSUE THREAD

**Issue by jornveltrop** [lisannevvliet/ethical-food-checker-pwa#26]
https://github.com/lisannevvliet/ethical-food-checker-pwa/blob/d6f2b61fba38ad03a728ecfa9dc402c2f194373c/static/service-worker.js#L14

Je kunt wat meer comments toevoegen aan je service-worker file, zodat het duidelijker wordt wat het doet.

**Comment by lisannevvliet** [comment]
Added comments to service worker.
