### ISSUE TITLE
Input field als pagination

### ISSUE THREAD

**Issue by jornveltrop** [lisannevvliet/ethical-food-checker-pwa#27]
https://github.com/lisannevvliet/ethical-food-checker-pwa/blob/e32560202464cb816a7c2722a33de5e14d5a5ec4/views/results.ejs#L47-L57

Ik twijfel of de bezoeker van de site een input field weet te gebruiken als pagina navigatie.

**Comment by lisannevvliet** [comment]
Valid point, will fix.

**Comment by lisannevvliet** [comment]
Sadly, I will not be able to implement this during the remaining time.
